### ISSUE TITLE
covariance parameter extraction and updating

### ISSUE THREAD

**Issue by topepo** [jpiironen/gplite#4]
I'm thinking about using `gplite` for the [Bayesian optimization](https://tune.tidymodels.org/reference/tune_bayes.html) done in the `tune` package. I'd like to pass in starting parameters since we run repeated GPs based in incremental updates to the data. My initial testing indicates that, for this application, taking a median or trimmed mean of the previous parameters is very helpful. 

The issue is that it is difficult to know the parameter values for the covariance function (programmatically). I'd like to extract them per iteration but that might be difficult when there are compound covariance functions. 

Can you make something like an `extract_parameters` function that could return a data frame of the parameters and their associated covariance function? An `update` method would also be nice.

For the example in the vignette, maybe something like this: 

```r
cf0 <- cf_const(magn = 5)
cf1 <- cf_lin(magn = 0.01)
cf2 <- cf_periodic(
  period = 12, 
  prior_period = prior_fixed(),
) * cf_sexp(
  lscale = 100,
  magn = 1, 
  prior_magn = prior_fixed()
)
cfs <- list(cf0, cf1, cf2)

data.frame(
  parameter = c("magn", "magn", "lscale", "magn"),
  value = c(5, 0.01, 100, 1),
  source = c("cf_const", "cf_lin", "cf_periodic", "cf_periodic"),
  index = c(1, 1, 2, 2)
)
```

or something similar to make them identifiable and updatable.

**Comment by jpiironen** [comment]
Hi. The package implements `get_param` and `set_param` functions. If you open the documentation (e.g. `?get_param`) there's an example about how to use them. If I understand correctly, these should satisfy your needs.

**Comment by jpiironen** [comment]
@topepo does this answer your question?

**Comment by topepo** [comment]
Yes. Thanks
